name: Cairo 1 tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'

  test-cairo:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v3
      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-lock: ./src/Scarb.lock


      - name: Install Universal Sierra Compiler
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/universal-sierra-compiler/master/scripts/install.sh | sh

      - name: Run scarb fmt check in src
        working-directory: src/
        run: scarb fmt --check
      - name: Run scarb test in src
        working-directory: src/
        run: scarb test

      - name: Run scarb fmt check in mutator_set
        working-directory: src/contracts/mutator_set
        run: scarb fmt --check
      - name: Run snforge test in mutator_set
        working-directory: src/contracts/mutator_set
        run: |
          export PATH="$PATH:$HOME/.local/bin"
          snforge test
